-- MySQL Script generated by MySQL Workbench
-- Tue May 20 22:18:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feh` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `feh`;

-- -----------------------------------------------------
-- Table `feh`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`marca` (
  `id` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `logo` VARCHAR(400) NULL,
  `descricao` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_marca_nome` (`nome`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`produtos` (
  `id` VARCHAR(36) NOT NULL,
  `marcaID` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `tags` VARCHAR(255) NULL,
  `adicional` VARCHAR(255) NULL,
  `foto1` VARCHAR(400) NOT NULL,
  `foto2` VARCHAR(400) NULL,
  `foto3` VARCHAR(400) NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `barcode` VARCHAR(50) NULL,
  `codsys` VARCHAR(50) NULL,
  `descricaocurta` VARCHAR(150) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_marca_idx` (`marcaID` ASC) VISIBLE,
  INDEX `idx_produtos_nome` (`nome`),
  INDEX `idx_produtos_barcode` (`barcode`),
  INDEX `idx_produtos_tipo` (`tipo`),
  CONSTRAINT `fk_produtos_marca`
    FOREIGN KEY (`marcaID`)
    REFERENCES `feh`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isEmailConfirmed` BOOLEAN NOT NULL DEFAULT FALSE,
  `companyId` VARCHAR(36) NULL,
  `foto` VARCHAR(500) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_user_email` (`email`),
  INDEX `idx_user_username` (`username`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`template` (
  `id` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `largura` INT NOT NULL,
  `altura` INT NOT NULL,
  `quant_imagem` INT NOT NULL DEFAULT 1,
  `img_fundo` VARCHAR(400) NULL,
  `fonte` VARCHAR(100) NULL,
  `texto_cabecalho` VARCHAR(500) NULL,
  `texto_rodape` VARCHAR(500) NULL,
  `midia` ENUM('D','I','V') NOT NULL COMMENT 'D=Digital, I=Impresso, V=Video',
  `dpi` INT NULL,
  `authorId` VARCHAR(36) NOT NULL,
  `description` VARCHAR(255) NULL,
  `conteudojson` JSON NULL,
  `carimbopreco` VARCHAR(100) NULL,
  `carimbotituloprod` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `userID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_models_User1_idx` (`userID` ASC) VISIBLE,
  INDEX `idx_template_nome` (`nome`),
  CONSTRAINT `fk_models_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `feh`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`empresa` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `logo` VARCHAR(400) NULL,
  `description` VARCHAR(500) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `usuarioID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_empresa_cnpj` (`cnpj`),
  INDEX `fk_Company_usuario1_idx` (`usuarioID` ASC) VISIBLE,
  INDEX `idx_empresa_name` (`name`),
  CONSTRAINT `fk_Company_usuario1`
    FOREIGN KEY (`usuarioID`)
    REFERENCES `feh`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`encarte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`encarte` (
  `id` VARCHAR(36) NOT NULL,
  `userID` VARCHAR(36) NOT NULL,
  `modelID` VARCHAR(36) NOT NULL,
  `empresaID` VARCHAR(36) NOT NULL,
  `encartejson` JSON NULL,
  `avisosencarte` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projeto_usuario1_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_projeto_modelo1_idx` (`modelID` ASC) VISIBLE,
  INDEX `fk_project_Company1_idx` (`empresaID` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_usuario1`
    FOREIGN KEY (`userID`)
    REFERENCES `feh`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_modelo1`
    FOREIGN KEY (`modelID`)
    REFERENCES `feh`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_Company1`
    FOREIGN KEY (`empresaID`)
    REFERENCES `feh`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`encarte_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`encarte_item` (
  `id` VARCHAR(36) NOT NULL,
  `produtoID` VARCHAR(36) NOT NULL,
  `projetoID` VARCHAR(36) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `valorpromo` DECIMAL(10,2) NULL,
  `valorantigo` DECIMAL(10,2) NULL,
  `regracompra` VARCHAR(255) NULL,
  `validadeprod` DATE NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itens_projeto_produtos1_idx` (`produtoID` ASC) VISIBLE,
  INDEX `fk_itens_projeto_projeto1_idx` (`projetoID` ASC) VISIBLE,
  CONSTRAINT `fk_itens_projeto_produtos1`
    FOREIGN KEY (`produtoID`)
    REFERENCES `feh`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_projeto_projeto1`
    FOREIGN KEY (`projetoID`)
    REFERENCES `feh`.`encarte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feh`.`produtouso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feh`.`produtouso` (
  `id` VARCHAR(36) NOT NULL,
  `ultimovalor` DECIMAL(10,2) NOT NULL,
  `descperson` VARCHAR(255) NULL,
  `produtoID` VARCHAR(36) NOT NULL,
  `empresaID` VARCHAR(36) NOT NULL,
  `ultimopreco` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtouso_produtos1_idx` (`produtoID` ASC) VISIBLE,
  INDEX `fk_produtouso_Company1_idx` (`empresaID` ASC) VISIBLE,
  CONSTRAINT `fk_produtouso_produtos1`
    FOREIGN KEY (`produtoID`)
    REFERENCES `feh`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtouso_Company1`
    FOREIGN KEY (`empresaID`)
    REFERENCES `feh`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Trigger para gerar UUID antes de inserir em cada tabela
DELIMITER $$

CREATE TRIGGER before_insert_marca
BEFORE INSERT ON `feh`.`marca` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_produtos
BEFORE INSERT ON `feh`.`produtos` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_user
BEFORE INSERT ON `feh`.`user` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_template
BEFORE INSERT ON `feh`.`template` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_empresa
BEFORE INSERT ON `feh`.`empresa` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_encarte
BEFORE INSERT ON `feh`.`encarte` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_encarte_item
BEFORE INSERT ON `feh`.`encarte_item` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

CREATE TRIGGER before_insert_produtouso
BEFORE INSERT ON `feh`.`produtouso` FOR EACH ROW
BEGIN
  IF NEW.id IS NULL THEN
    SET NEW.id = UUID();
  END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
