-- AlterTable
ALTER TABLE "User" 
ADD COLUMN "foto" VARCHAR(500),
ADD COLUMN "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "deletedAt" TIMESTAMP; 